# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  backend:
    # Configuration for building the docker image for the backend service
    image: mckang/backend
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  frontend:
    image: mckang/frontend
    ports:
      - "80:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - backend
    networks:
      - frontend  

  # Database Service (Mysql)
  db:
    image: mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - backend  

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    