all:
  children:
    manager:
      hosts:
        manager:
          ansible_ssh_host: 10.0.3.150
    worker:
      hosts:
        team1-02:
          ansible_ssh_host: 10.0.3.19        
        team1-03:
          ansible_ssh_host: 10.0.3.237        
  vars:
    ansible_user: "ansible"
    ansible_ssh_private_key_file: "/Users/thomas/Desktop/gcu-summer/sample/polling-app-deploy/secrets/team1-ansible"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
