---
# VM_IMAGE_NAME: 
# VM_VOLUME_OS_SIZE: 10
# VM_KEY_NAME: 
# VM_SG_NAMES: 
# VM_FLAVOR_NAME: 
# VM_META: ansible=true,group=test
# VM_DATA_VOLUMES:
#   - device: /dev/vdb
#     mount: /data1
#     size: 15
# VM_NETWORKS:
#   - net-id: 
# VM_ANSIBLE_PUB_KEY_FILE: 
VM_USERDATA_TEMPLATE_FILE: userdata.j2
VM_ADD_HOST_GROUPS:
  - ansible
  - now_added
VM_ADD_HOST_VARS: {}