  - set_fact:        
      VM_DATA_VOLUMES: "{{ [] }}"
    when: VM_DATA_VOLUMES is not defined
  - set_fact:        
      VM_ANSIBLE_PUB_KEY: "{{ lookup('file', VM_ANSIBLE_PUB_KEY + '') }}"
  - set_fact:  
      VM_USERDATA: "{{ lookup('template', VM_USERDATA_TEMPLATE + '') }}"
  - debug:
      var: VM_USERDATA     